Traceback (most recent call last):
  File "/Users/parisasokuti/.pyenv/versions/3.7.17/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/parisasokuti/.pyenv/versions/3.7.17/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/parisasokuti/my git repo/DS_project/backend/server.py", line 10, in <module>
    from network import NetworkManager
ModuleNotFoundError: No module named 'network'
